apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: staging
namePrefix: staging-
nameSuffix: -vbeta.1
images:
- name: lordofthejars/pacman-kikd
  newTag: 1.2.0-beta